### ISSUE TITLE
Excessive syslog messages from racoon

### ISSUE THREAD

**Issue by bleach** [SAP/ipsec-release#4]
## The problem 

We get lots of these messages:

```racoon [job=router index=1]  alg_oakley_hmacdef_one(hmac_sha2_256 size=36)```

We don't get any benefit from them, but we see 60,000 of them per hour in our production logsearch and we'd like to remove them to reduce noise and reduce log storage costs.

Could you stop these messages appearing? Would you accept a PR to do this if it stopped the messages on all installations?

## Tech details

From a glance at the source, the messages are emitted in code inside `#ifdefs` like this:

```
#ifdef ENABLE_STATS
        gettimeofday(&end, NULL);
        syslog(LOG_NOTICE, "%s(%s size=%zu): %8.6f", __func__,
                f->name, buf->l, timedelta(&start, &end));
#endif
```

Which means that [this line](https://github.com/SAP/ipsec-release/blob/c037e288098a6465cacc16a7fa76207a25743ab0/packages/racoon/packaging#L37) would need to be removed so that `--enable-stats` is not set.

**Comment by marwinski** [comment]
Thank for for making this suggestion. After a quick scan of the racoon code I don't see a reason for not removing this option.

**Comment by bleach** [comment]
Thanks @marwinski - we'll see if we get time to do it.

**Comment by voelzmo** [comment]
Seems like this has been released in v2+. Please re-open if the issue persists.
